version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: container_mysql_orange_graph_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orange_graph_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: