spring:
  output:
    ansi:
      enabled: always

  application:
    name: orange-graph

  datasource:
    url: jdbc:mysql://localhost:3306/orange_graph_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true

  h2:
    console:
      enabled: true

  
  #datasource:
    #url: jdbc:h2:mem:orange_graph_db
    #username: sa
    #password: password
    #driverClassName: org.h2.Driver

  #jpa:
   # database-platform: org.hibernate.dialect.H2Dialect

  #configuração H2 caso tenha problemas com o docker