spring:
  output:
    ansi:
      enabled: always

  application:
    name: orange-graph

  datasource:
    url: jdbc:h2:mem:orange_graph_db
    username: sa
    password: password
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create

  h2:
    console:
      enabled: true